import type {
  User,
  Track,
  Collaboration,
  Order,
  Review,
  Promotion,
  Dispute,
  Conversation,
  Message,
  AppNotification,
  PlanKey,
  LicenseKey,
} from '@/types';

const now = Date.now();
const day = 86400000;

const avatar = (name: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(
    name
  )}&background=1DB954&color=fff&size=128`;

export const SEED_USERS: User[] = [
  {
    id: 'user_01',
    name: 'Aarav Sharma',
    email: 'aarav@demo.music',
    avatar: avatar('Aarav Sharma'),
    role: 'Producer',
    plan: 'free',
    bio: 'Bedroom producer chasing the perfect lo-fi loop. Always down to collab.',
    headline: 'Music Producer • Free Creator',
    location: 'Mumbai',
    skills: ['Ableton', 'Mixing', 'Lo-fi', 'Sampling'],
    genres: ['Lo-fi', 'Hip-hop', 'Chill'],
    rating: 4.3,
    agreedToTerms: false,
    createdAt: now - 45 * day,
  },
  {
    id: 'user_02',
    name: 'Priya Menon',
    email: 'priya@demo.music',
    avatar: avatar('Priya Menon'),
    role: 'Vocalist',
    plan: 'pro',
    bio: 'Session vocalist. I sing pop, R&B, and the occasional Bollywood hook.',
    headline: 'Vocalist • Pro Creator',
    location: 'Bangalore',
    skills: ['Vocals', 'Songwriting', 'Topline', 'Harmonies'],
    genres: ['Pop', 'R&B', 'Bollywood'],
    rating: 4.8,
    agreedToTerms: false,
    createdAt: now - 120 * day,
  },
  {
    id: 'user_03',
    name: 'Rohan Kapoor',
    email: 'rohan@demo.music',
    avatar: avatar('Rohan Kapoor'),
    role: 'Mixing Engineer',
    plan: 'studio',
    bio: 'Studio owner. 10 years mixing rock, metal, and indie.',
    headline: 'Mixing Engineer • Studio Creator',
    location: 'Delhi',
    skills: ['Mixing', 'Mastering', 'Pro Tools', 'Analog Gear'],
    genres: ['Rock', 'Metal', 'Indie'],
    rating: 4.9,
    agreedToTerms: true,
    agreedAt: now - 119 * day,
    createdAt: now - 400 * day,
  },
  {
    id: 'user_04',
    name: 'Ananya Iyer',
    email: 'ananya@demo.music',
    avatar: avatar('Ananya Iyer'),
    role: 'Listener',
    plan: 'free_listener',
    bio: 'Music lover. Playlist curator. Always looking for new sounds.',
    headline: 'Music Lover',
    location: 'Chennai',
    skills: ['Playlists', 'Curation'],
    genres: ['Indie', 'Pop', 'Electronic'],
    rating: 4.5,
    agreedToTerms: true,
    agreedAt: now - 60 * day,
    createdAt: now - 90 * day,
  },
  {
    id: 'user_05',
    name: 'Vikram Singh',
    email: 'vikram@demo.music',
    avatar: avatar('Vikram Singh'),
    role: 'Listener',
    plan: 'premium_listener',
    bio: 'Audiophile. FLAC only. Yes, I can hear the difference.',
    headline: 'Audiophile • Premium Listener',
    location: 'Pune',
    skills: ['Audio Review', 'Critical Listening'],
    genres: ['Jazz', 'Classical', 'Ambient'],
    rating: 4.6,
    agreedToTerms: true,
    agreedAt: now - 55 * day,
    createdAt: now - 200 * day,
  },
  {
    id: 'user_06',
    name: 'Meera Nair',
    email: 'meera@demo.music',
    avatar: avatar('Meera Nair'),
    role: 'Brand Manager',
    plan: 'brand',
    bio: 'Looking for fresh tracks for TuneCo ad campaigns.',
    headline: 'Brand Manager @ TuneCo',
    location: 'Kochi',
    skills: ['Marketing', 'Licensing', 'Brand Strategy'],
    genres: ['Pop', 'Electronic', 'Hip-hop'],
    rating: 4.2,
    agreedToTerms: true,
    agreedAt: now - 30 * day,
    createdAt: now - 150 * day,
  },
  {
    id: 'user_07',
    name: 'Karan Malhotra',
    email: 'karan@demo.music',
    avatar: avatar('Karan Malhotra'),
    role: 'A&R',
    plan: 'label',
    bio: 'A&R at BeatHouse Records. Signing the next big thing.',
    headline: 'A&R @ BeatHouse Records',
    location: 'Mumbai',
    skills: ['A&R', 'Scouting', 'Contracts', 'Artist Development'],
    genres: ['Hip-hop', 'Pop', 'R&B'],
    rating: 4.7,
    agreedToTerms: true,
    agreedAt: now - 80 * day,
    createdAt: now - 500 * day,
  },
  {
    id: 'user_08',
    name: 'Zara Khan',
    email: 'zara@demo.music',
    avatar: avatar('Zara Khan'),
    role: 'Artist',
    plan: 'free',
    bio: 'Bedroom pop artist. I write sad songs you can dance to.',
    headline: 'Bedroom Pop Artist • Free Creator',
    location: 'Hyderabad',
    skills: ['Songwriting', 'Vocals', 'Guitar', 'Production'],
    genres: ['Bedroom Pop', 'Indie', 'Dream Pop'],
    rating: 4.4,
    agreedToTerms: true,
    agreedAt: now - 20 * day,
    createdAt: now - 25 * day,
  },
  {
    id: 'user_09',
    name: 'Dev Patel',
    email: 'dev@demo.music',
    avatar: avatar('Dev Patel'),
    role: 'Producer',
    plan: 'pro',
    bio: 'Hip-hop producer. Boom bap to trap. Let\'s make hits.',
    headline: 'Hip-hop Producer • Pro Creator',
    location: 'Ahmedabad',
    skills: ['FL Studio', 'Beat Making', 'Trap', 'Boom Bap'],
    genres: ['Hip-hop', 'Trap', 'Rap'],
    rating: 4.5,
    agreedToTerms: true,
    agreedAt: now - 70 * day,
    createdAt: now - 220 * day,
  },
  {
    id: 'user_10',
    name: 'Admin User',
    email: 'admin@demo.music',
    avatar: avatar('Admin User'),
    role: 'Moderator',
    plan: 'admin',
    bio: 'Platform moderator. Here to keep things clean.',
    headline: 'Platform Moderator',
    location: 'Remote',
    skills: ['Moderation', 'Support'],
    genres: ['All'],
    rating: 5.0,
    agreedToTerms: true,
    agreedAt: now - 365 * day,
    createdAt: now - 365 * day,
  },
];

const trackTitles = [
  ['Midnight Rain', 'Lo-fi', 'user_01', 'open_collab', 0],
  ['Neon Dreams', 'Pop', 'user_02', 'credit_only', 199],
  ['Broken Strings', 'Rock', 'user_03', 'commercial', 499],
  ['Sunset Boulevard', 'Indie', 'user_08', 'open_collab', 0],
  ['Trap House', 'Hip-hop', 'user_09', 'commercial', 399],
  ['Ocean Eyes', 'Dream Pop', 'user_02', 'non_commercial', 0],
  ['City Lights', 'Electronic', 'user_01', 'credit_only', 149],
  ['Golden Hour', 'Bedroom Pop', 'user_08', 'open_collab', 0],
  ['Bass Drop', 'Trap', 'user_09', 'commercial', 349],
  ['Acoustic Morning', 'Indie', 'user_03', 'all_rights', 0],
  ['Velvet Sky', 'R&B', 'user_02', 'commercial', 599],
  ['Lo-fi Sunday', 'Lo-fi', 'user_01', 'open_collab', 0],
  ['Electric Pulse', 'Electronic', 'user_09', 'credit_only', 249],
  ['Paper Planes', 'Indie', 'user_08', 'custom', 0],
  ['Deep Waters', 'Ambient', 'user_03', 'non_commercial', 0],
  ['Firestarter', 'Rock', 'user_03', 'commercial', 449],
  ['Moonlit', 'Dream Pop', 'user_02', 'credit_only', 179],
  ['Streets of Delhi', 'Hip-hop', 'user_09', 'commercial', 299],
  ['Coastal Drive', 'Chill', 'user_01', 'open_collab', 0],
  ['Starlight', 'Pop', 'user_08', 'credit_only', 199],
] as const;

export const SEED_TRACKS: Track[] = trackTitles.map((t, i) => {
  const [title, genre, userId, license, price] = t;
  return {
    id: `track_${String(i + 1).padStart(2, '0')}`,
    userId,
    title,
    url: `https://picsum.photos/seed/${encodeURIComponent(title)}/800/800`,
    coverUrl: `https://picsum.photos/seed/${encodeURIComponent(title)}-cover/400/400`,
    plays: Math.floor(Math.random() * 5000) + 100,
    genre,
    bpm: 70 + Math.floor(Math.random() * 80),
    license: license as LicenseKey,
    price,
    description: `A ${genre.toLowerCase()} track by ${
      SEED_USERS.find((u) => u.id === userId)?.name
    }.`,
    createdAt: now - Math.floor(Math.random() * 100) * day,
    promoted: i % 4 === 0,
    promoType: i % 4 === 0 ? 'featured' : undefined,
  };
});

export const SEED_COLLABORATIONS: Collaboration[] = [
  {
    id: 'collab_01',
    trackId: 'track_01',
    initiatorId: 'user_01',
    contributorId: 'user_02',
    role: 'Vocalist',
    status: 'active',
    createdAt: now - 10 * day,
  },
  {
    id: 'collab_02',
    trackId: 'track_03',
    initiatorId: 'user_03',
    contributorId: 'user_09',
    role: 'Producer',
    status: 'pending',
    createdAt: now - 8 * day,
  },
  {
    id: 'collab_03',
    trackId: 'track_05',
    initiatorId: 'user_09',
    contributorId: 'user_08',
    role: 'Songwriter',
    status: 'active',
    createdAt: now - 6 * day,
  },
  {
    id: 'collab_04',
    trackId: 'track_02',
    initiatorId: 'user_02',
    contributorId: 'user_01',
    role: 'Producer',
    status: 'completed',
    createdAt: now - 30 * day,
  },
  {
    id: 'collab_05',
    trackId: 'track_09',
    initiatorId: 'user_09',
    contributorId: 'user_02',
    role: 'Topline',
    status: 'active',
    createdAt: now - 4 * day,
  },
  {
    id: 'collab_06',
    trackId: 'track_08',
    initiatorId: 'user_08',
    contributorId: 'user_03',
    role: 'Mixing',
    status: 'pending',
    createdAt: now - 2 * day,
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'order_01',
    buyerId: 'user_06',
    sellerId: 'user_02',
    trackId: 'track_11',
    amount: 599,
    commission: 90,
    status: 'completed',
    createdAt: now - 5 * day,
  },
  {
    id: 'order_02',
    buyerId: 'user_07',
    sellerId: 'user_03',
    trackId: 'track_03',
    amount: 499,
    commission: 50,
    status: 'completed',
    createdAt: now - 12 * day,
  },
  {
    id: 'order_03',
    buyerId: 'user_06',
    sellerId: 'user_09',
    trackId: 'track_05',
    amount: 399,
    commission: 60,
    status: 'pending',
    createdAt: now - 2 * day,
  },
  {
    id: 'order_04',
    buyerId: 'user_07',
    sellerId: 'user_02',
    trackId: 'track_02',
    amount: 199,
    commission: 30,
    status: 'completed',
    createdAt: now - 20 * day,
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: 'review_01',
    reviewerId: 'user_02',
    revieweeId: 'user_01',
    rating: 5,
    comment: 'Great loops! Super easy to work with.',
    createdAt: now - 3 * day,
  },
  {
    id: 'review_02',
    reviewerId: 'user_01',
    revieweeId: 'user_02',
    rating: 5,
    comment: 'Priya\'s vocals are next level. Highly recommend.',
    createdAt: now - 5 * day,
  },
  {
    id: 'review_03',
    reviewerId: 'user_09',
    revieweeId: 'user_03',
    rating: 5,
    comment: 'Rohan mixed my track perfectly. Pro gear, pro ears.',
    createdAt: now - 8 * day,
  },
  {
    id: 'review_04',
    reviewerId: 'user_08',
    revieweeId: 'user_09',
    rating: 4,
    comment: 'Dev\'s beats slap. Fast turnaround too.',
    createdAt: now - 10 * day,
  },
  {
    id: 'review_05',
    reviewerId: 'user_03',
    revieweeId: 'user_02',
    rating: 5,
    comment: 'Best session vocalist I\'ve worked with.',
    createdAt: now - 15 * day,
  },
  {
    id: 'review_06',
    reviewerId: 'user_02',
    revieweeId: 'user_09',
    rating: 4,
    comment: 'Solid production. Would collab again.',
    createdAt: now - 18 * day,
  },
  {
    id: 'review_07',
    reviewerId: 'user_01',
    revieweeId: 'user_08',
    rating: 4,
    comment: 'Zara\'s songwriting is really unique.',
    createdAt: now - 20 * day,
  },
  {
    id: 'review_08',
    reviewerId: 'user_09',
    revieweeId: 'user_08',
    rating: 5,
    comment: 'Killer melodies. Very professional.',
    createdAt: now - 22 * day,
  },
  {
    id: 'review_09',
    reviewerId: 'user_05',
    revieweeId: 'user_03',
    rating: 5,
    comment: 'Mixing quality is top tier.',
    createdAt: now - 25 * day,
  },
  {
    id: 'review_10',
    reviewerId: 'user_06',
    revieweeId: 'user_09',
    rating: 4,
    comment: 'Delivered on time. Great communication.',
    createdAt: now - 28 * day,
  },
  {
    id: 'review_11',
    reviewerId: 'user_07',
    revieweeId: 'user_02',
    rating: 5,
    comment: 'A&R approved. This girl is going places.',
    createdAt: now - 30 * day,
  },
  {
    id: 'review_12',
    reviewerId: 'user_04',
    revieweeId: 'user_01',
    rating: 4,
    comment: 'Love the vibe of Aarav\'s tracks.',
    createdAt: now - 35 * day,
  },
];

export const SEED_PROMOTIONS: Promotion[] = [
  {
    id: 'promo_01',
    userId: 'user_01',
    trackId: 'track_01',
    type: 'featured',
    impressions: 12400,
    clicks: 890,
    createdAt: now - 7 * day,
  },
  {
    id: 'promo_02',
    userId: 'user_02',
    trackId: 'track_02',
    type: 'sponsored',
    impressions: 8900,
    clicks: 620,
    createdAt: now - 5 * day,
  },
  {
    id: 'promo_03',
    userId: 'user_09',
    trackId: 'track_05',
    type: 'promoted',
    impressions: 5600,
    clicks: 340,
    createdAt: now - 3 * day,
  },
  {
    id: 'promo_04',
    userId: 'user_03',
    trackId: 'track_03',
    type: 'featured',
    impressions: 15200,
    clicks: 1100,
    createdAt: now - 10 * day,
  },
  {
    id: 'promo_05',
    userId: 'user_08',
    trackId: 'track_08',
    type: 'promoted',
    impressions: 3200,
    clicks: 180,
    createdAt: now - 2 * day,
  },
];

export const SEED_DISPUTES: Dispute[] = [
  {
    id: 'dispute_01',
    filedBy: 'user_06',
    against: 'user_02',
    status: 'mediating',
    evidence: 'Track was delivered late and not as described.',
    deadline: now + 5 * day,
    createdAt: now - 2 * day,
  },
  {
    id: 'dispute_02',
    filedBy: 'user_09',
    against: 'user_03',
    status: 'filed',
    evidence: 'Mixing revisions exceeded agreed scope.',
    deadline: now + 7 * day,
    createdAt: now - 1 * day,
  },
  {
    id: 'dispute_03',
    filedBy: 'user_01',
    against: 'user_08',
    status: 'resolved',
    evidence: 'Stems not provided after payment.',
    deadline: now - 3 * day,
    createdAt: now - 12 * day,
  },
];

const convoDefs: Array<[string, string, string]> = [
  ['user_01', 'user_02', 'Hey! Loved your vocal on Neon Dreams 🎤'],
  ['user_01', 'user_09', 'Yo, want to collab on a trap beat?'],
  ['user_02', 'user_03', 'Can you mix my next single?'],
  ['user_08', 'user_09', 'Send me that stem pack when you can'],
  ['user_03', 'user_09', 'Track sounds fire after the mixdown'],
  ['user_06', 'user_02', 'Interested in licensing Velvet Sky for an ad'],
  ['user_07', 'user_03', 'A&R here — want to talk contract?'],
  ['user_04', 'user_01', 'Your lo-fi playlist is on repeat!'],
];

export const SEED_CONVERSATIONS: Conversation[] = convoDefs.map((c, i) => ({
  id: `convo_${String(i + 1).padStart(2, '0')}`,
  participants: { [c[0]]: true, [c[1]]: true },
  lastMessage: c[2],
  updatedAt: now - (i + 1) * 3600000,
}));

export const SEED_MESSAGES: Record<string, Record<string, Message>> = {};
convoDefs.forEach((c, i) => {
  const convoId = `convo_${String(i + 1).padStart(2, '0')}`;
  const m1 = `${convoId}_msg_01`;
  const m2 = `${convoId}_msg_02`;
  const m3 = `${convoId}_msg_03`;
  SEED_MESSAGES[convoId] = {
    [m1]: {
      id: m1,
      from: c[0],
      text: 'Hey! How are you?',
      createdAt: now - (i + 1) * 7200000,
      read: true,
    },
    [m2]: {
      id: m2,
      from: c[1],
      text: 'Doing great! Working on something new.',
      createdAt: now - (i + 1) * 5400000,
      read: true,
    },
    [m3]: {
      id: m3,
      from: c[0],
      text: c[2],
      createdAt: now - (i + 1) * 3600000,
      read: i % 2 === 0,
    },
  };
});

export const SEED_NOTIFICATIONS: Record<
  string,
  Record<string, AppNotification>
> = {
  user_01: {
    notif_01: {
      id: 'notif_01',
      type: 'message',
      title: 'New message from Priya',
      message: 'Loved your vocal on Neon Dreams 🎤',
      link: '/chat',
      read: false,
      createdAt: now - 3600000,
    },
    notif_02: {
      id: 'notif_02',
      type: 'collab',
      title: 'Collab request',
      message: 'Dev Patel wants to collab on a trap beat.',
      link: '/collaborate',
      read: false,
      createdAt: now - 7200000,
    },
    notif_03: {
      id: 'notif_03',
      type: 'review',
      title: 'New 5★ review',
      message: 'Priya Menon rated you 5 stars!',
      link: '/profile/user_01',
      read: true,
      createdAt: now - 86400000,
    },
  },
  user_02: {
    notif_04: {
      id: 'notif_04',
      type: 'payment',
      title: 'Payment received',
      message: '₹599 from Meera Nair for Velvet Sky.',
      link: '/dashboard',
      read: false,
      createdAt: now - 1800000,
    },
    notif_05: {
      id: 'notif_05',
      type: 'message',
      title: 'New message from Aarav',
      message: 'Hey! Loved your vocal on Neon Dreams 🎤',
      link: '/chat',
      read: false,
      createdAt: now - 3600000,
    },
  },
  user_09: {
    notif_06: {
      id: 'notif_06',
      type: 'collab',
      title: 'Collab accepted',
      message: 'Zara Khan accepted your collab request.',
      link: '/collaborate',
      read: false,
      createdAt: now - 5400000,
    },
  },
};


export const SEED_SUBSCRIPTIONS: Record<string, { plan: PlanKey; startDate: number; endDate: number }> = {
  user_02: { plan: 'pro', startDate: now - 30 * day, endDate: now + 335 * day },
  user_03: { plan: 'studio', startDate: now - 90 * day, endDate: now + 275 * day },
  user_05: {
    plan: 'premium_listener',
    startDate: now - 20 * day,
    endDate: now + 345 * day,
  },
  user_09: { plan: 'pro', startDate: now - 15 * day, endDate: now + 350 * day },
};